const express = require('express')

const app = express()

const register = require('./routes/admin/register')
const {app: loginRoutes} = require('./routes/login')
const dashboard = require('./routes/dashboard')
const add_product = require('./routes/admin/productos/add_product')
const update_product = require('./routes/admin/productos/update_products')
const delete_product = require('./routes/admin/productos/delete_product')
const show_products = require('./routes/show_product')
const add_table = require('./routes/admin/mesas/add_table')
const new_order = require('./routes/mesero/new_order')
const update_order = require('./routes/mesero/update_order')
const update_order_id = require('./routes/mesero/update_order_id')
const dish_ready = require('./routes/cocinero/dish_ready')
const dish_ready_id = require('./routes/cocinero/dish_ready_id')
const show_pending_dishes = require('./routes/show_pending_dishes')
const show_ready_dishes = require('./routes/show_ready_dishes')

app.use(register)
app.use(loginRoutes)
app.use(dashboard)
app.use(add_product)
app.use(update_product)
app.use(delete_product)
app.use(show_products)
app.use(add_table)
app.use(new_order)
app.use(update_order)
app.use(update_order_id)
app.use(dish_ready)
app.use(dish_ready_id)
app.use(show_pending_dishes)
app.use(show_ready_dishes)

app.listen(3000)
console.log("Server en puerto 3000")